import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
<<<<<<< HEAD
import { CartProvider } from "@/Context/CardContext";
=======
>>>>>>> 1fe0014feacf081cd9f996ae25323c7a8c5343e9

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "Food Delivery App",
=======
  title: "Create Next App",
>>>>>>> 1fe0014feacf081cd9f996ae25323c7a8c5343e9
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
<<<<<<< HEAD
        <CartProvider>{children}</CartProvider>
=======
        {children}
>>>>>>> 1fe0014feacf081cd9f996ae25323c7a8c5343e9
      </body>
    </html>
  );
}
